spring:
  application:
      name: auth-server

  redis:
      host: 127.0.0.1




server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

security:
  oauth2:
    resource:
      filter-order: 3