spring:
  application:
    name: smart-home-kitchen-server

  redis:
    host: 192.168.85.208

server:
  port: 8763

management.security.enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.85.208:8761/eureka/


feign:
  hystirx:
    enable: true

security:
  oauth2:
    resource:
      id: smart-home-kitchen-server
      user-info-uri: http://192.168.85.208:9000/auth/user/current
      prefer-token-info: false