server:
  port: 8761

eureka:
  instance:
  # 配置主机名
    hostname: 192.168.85.208
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  server:
    enable-self-preservation: false