spring:
  application:
  # 设置服务名
    name: smart-home-zuul-gateway

eureka:
  client:
    serviceUrl:
    # 对应注册中心url
      defaultZone: http://localhost:8761/eureka/


server:
  port: 9000

#zuul:
#  routes:
#    city:
#      path: /city/**
#      serviceId: msa-weather-collection-eureka-feign
#
#    data:
#      path: /data/**
#      serviceId:  micro-weather-data-eureka-client



security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/smarthome/oauth/token
      user-authorization-uri: http://localhost:${server.port}/smarthome/oauth/authorize
      client-id: webapp
    resource:
      user-info-uri: http://localhost:${server.port}/smarthome/user
      prefer-token-info: false

